import type { Metadata } from "next";
import { Nunito_Sans } from "next/font/google";
import "./globals.css";
import { AppRouterCacheProvider } from '@mui/material-nextjs/v13-appRouter'
import { Container, ThemeProvider } from "@mui/material";
import theme from "@/components/mui/theme";
import Header from "@/components/header/header";
import { Toaster } from 'react-hot-toast';


const inter = Nunito_Sans({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Get Published",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
      <AppRouterCacheProvider>
          <ThemeProvider theme={theme}>     
              <Header />
              <Container sx={{pt: "6rem"}}>
                  {children}
              </Container>       
          </ThemeProvider>
      </AppRouterCacheProvider>
      </body>
    </html>
  );
}
